name: transformer-gpu
channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.5.1
      - -e .[dev]
